name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main  # Esto ejecutará el workflow cuando se haga un push a la rama `main`

jobs:
  build:
    runs-on: ubuntu-latest  # Esto especifica que el job se ejecutará en una máquina Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Esto obtiene el código de tu repositorio

      - name: Set up .NET
        uses: actions/setup-dotnet@v1  # Configura la versión de .NET que necesitas
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore  # Esto instala las dependencias de tu proyecto

      - name: Build application
        run: dotnet build --configuration Release  # Esto construye tu aplicación

      - name: Publish application
        run: dotnet publish --configuration Release --output ./published  # Esto publica la aplicación

      - name: Deploy to server (ejemplo de despliegue)
        run: |
          scp -r ./published username@server:/path/to/deploy  # Comando para desplegar (lo reemplazarás con tu servidor)
